backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:

  # ===================
  # NOTICIAS
  # ===================
  - name: "noticias"
    label: "Noticias"
    file: "src/data/noticias.json"
    format: "json"
    fields:
      - label: "Noticias"
        name: "items"
        widget: "list"
        fields:
          - { label: "ID", name: "id", widget: "number" }
          - { label: "Título", name: "titulo", widget: "string" }
          - { label: "Texto", name: "texto", widget: "text", required: false }
          - { label: "Imagen", name: "imagen", widget: "image", required: false }
          - { label: "Link", name: "link", widget: "string", required: false }

  # ===================
  # GALERÍA
  # ===================
  - name: "multimedia"
    label: "Galería Multimedia"
    file: "src/data/multimedia.json"
    format: "json"
    fields:
      - label: "Galerías"
        name: "items"
        widget: "list"
        fields:
          - { label: "Descripción", name: "descripcion", widget: "string" }
          - label: "Fotos"
            name: "fotos"
            widget: "list"
            field:
              { label: "Imagen", name: "image", widget: "image" }
