backend:
  name: github
  repo: Quisniaver/SindicatoPlantaMantoverde
  branch: main
  base_url: https://cms-auth.nico-vegav.workers.dev
  auth_endpoint: auth




media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "noticias"
    label: "Noticias"
    files:
      - name: "noticias"
        label: "Listado de noticias"
        file: "content/noticias.json"
        format: "json"
        fields:
          - label: "Noticias"
            name: "items"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "number" }
              - { label: "Título", name: "titulo", widget: "string" }
              - { label: "Texto", name: "texto", widget: "text", required: false }
              - { label: "Imagen", name: "imagen", widget: "image", required: false }
              - { label: "Link", name: "link", widget: "string", required: false }

  - name: "multimedia"
    label: "Galería Multimedia"
    files:
      - name: "multimedia"
        label: "Galerías"
        file: "content/multimedia.json"
        format: "json"
        fields:
          - label: "Galerías"
            name: "items"
            widget: "list"
            fields:
              - { label: "Descripción", name: "descripcion", widget: "string" }
              - label: "Fotos"
                name: "fotos"
                widget: "list"
                field:
                  { label: "Imagen", name: "image", widget: "image" }
